/**
 * @fileoverview gRPC-Web generated client stub for currencyconverter
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.0
// source: currency_converter.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as currency_converter_pb from './currency_converter_pb'; // proto import: "currency_converter.proto"


export class CurrencyConverterClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'text';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorConvertCurrency = new grpcWeb.MethodDescriptor(
    '/currencyconverter.CurrencyConverter/ConvertCurrency',
    grpcWeb.MethodType.UNARY,
    currency_converter_pb.ConvertCurrencyRequest,
    currency_converter_pb.ConvertCurrencyResponse,
    (request: currency_converter_pb.ConvertCurrencyRequest) => {
      return request.serializeBinary();
    },
    currency_converter_pb.ConvertCurrencyResponse.deserializeBinary
  );

  convertCurrency(
    request: currency_converter_pb.ConvertCurrencyRequest,
    metadata?: grpcWeb.Metadata | null): Promise<currency_converter_pb.ConvertCurrencyResponse>;

  convertCurrency(
    request: currency_converter_pb.ConvertCurrencyRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: currency_converter_pb.ConvertCurrencyResponse) => void): grpcWeb.ClientReadableStream<currency_converter_pb.ConvertCurrencyResponse>;

  convertCurrency(
    request: currency_converter_pb.ConvertCurrencyRequest,
    metadata?: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: currency_converter_pb.ConvertCurrencyResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/currencyconverter.CurrencyConverter/ConvertCurrency',
        request,
        metadata || {},
        this.methodDescriptorConvertCurrency,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/currencyconverter.CurrencyConverter/ConvertCurrency',
    request,
    metadata || {},
    this.methodDescriptorConvertCurrency);
  }

}

