version: '3.8'

services:
  currency-converter:
    build:
      context: application-currency-converter-services
    container_name: currency-converter-service
    ports:
      - "50051:50051"
    depends_on:
      - grpc-web-proxy

  grpc-web-proxy:
    build:
      context: ./grpc-web-proxy
    container_name: grpc-web-proxy
    ports:
      - "8081:8081"
